next (#17)

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -30,6 +30,27 @@ jobs:
     - name: Checkout code
       uses: actions/checkout@v2
 
+    - name: Check PR branch status
+      id: test-commit-status-check
+      run: |
+          # Get the last associated pull request with the current merge commit
+          PULLS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/pulls")
+          PR_NUMBER=$(echo "$PULLS" | jq -r '.[-1].number')
+
+          # Fetch the last commit SHA, from the original commits list of the associated PR branch
+          COMMITS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}/commits")
+          LAST_COMMIT=$(echo "$COMMITS" | jq -r '.[-1].sha')
+
+          # Look for failures in the checks of the commits
+          # One single failure will consider the checks failed, no failures (that may include skipped tests) will consider them a success
+          CHECK_RUNS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/commits/$LAST_COMMIT/check-runs")
+          LAST_PR_COMMIT_CHECKS_STATUS=$(echo "$CHECK_RUNS" | jq -r '[ .check_runs[] | select(.conclusion == "failure") | .conclusion] | first // "success"')
+
+          # Save value as step outputs
+          echo "STATUS=$LAST_PR_COMMIT_CHECKS_STATUS" >> "$GITHUB_OUTPUT"
+
+      if: github.event_name == 'push'
+
     - name: Run test on PR
       id: run-test-pr
       run: |
@@ -41,48 +62,7 @@ jobs:
             echo "PR Condition is not 'success'. Failing the step."
             exit 1
           fi
-      if: github.event_name == 'pull_request'
-
-
-    - name: Check PR branch status
-      id: test-commit-status-check
-      run: |
-          # Extract the pull request number from the GitHub event payload
-          PULLS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/pulls")
-          echo $PULLS
-          PR_NUMBER=$(echo "$PULLS" | jq -r '.[-1].number')
-          echo "PR_NUMBER $PR_NUMBER"
-
-          # Fetch the commits in the pull request
-          COMMITS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}/commits")
-          echo "LAST COMMITS $COMMITS"
-
-          # Extract the SHA of the last commit in the pull request
-          LAST_COMMIT=$(echo "$COMMITS" | jq -r '.[-1].sha')
-          echo "LAST COMMIT $LAST_COMMIT"
-
-          # Look for failures in the checks of the commits
-          CHECK_RUNS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/commits/$LAST_COMMIT/check-runs")
-          LAST_PR_COMMIT_CHECKS_STATUS=$(echo "$CHECK_RUNS" | jq -r '[ .check_runs[] | select(.conclusion == "failure") | .conclusion] | first // "success"')
-
-          echo "STATUS=$LAST_PR_COMMIT_CHECKS_STATUS" >> "$GITHUB_OUTPUT"
-          echo "LAST_PR_COMMIT_CHECKS_STATUS $LAST_PR_COMMIT_CHECKS_STATUS"
-
-      if: github.event_name == 'push'
-
-
-    - name: Run test on deploy
-      id: run-test-deploy
-      run: |
-          echo  $(ls ${GITHUB_WORKSPACE})
-          CONDITION=$(cat ${GITHUB_WORKSPACE}/condition)
-          if [ "$CONDITION" == "success" ]; then
-            echo "PR Condition is 'success'. Continuing with the step."
-          else
-            echo "PR Condition is not 'success'. Failing the step."
-            exit 1
-          fi
-      if: github.event_name == 'push' && steps.test-commit-status-check.outputs.STATUS == 'failure'
+      if: github.event_name == 'pull_request' || (github.event_name == 'push' && steps.test-commit-status-check.outputs.STATUS == 'failure')
 
   deploy:
     needs: test
