next

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -35,11 +35,11 @@ jobs:
       run: |
           echo  $(ls ${GITHUB_WORKSPACE})
           CONDITION=$(cat ${GITHUB_WORKSPACE}/condition)
-          if [ "$CONDITION" ==   "fail" ]; then
-            echo "PR Condition is 'fail'. Failing the step."
-            exit 1
+          if [ "$CONDITION" == "success" ]; then
+            echo "PR Condition is 'success'. Continuing with the step."
           else
-            echo "PR Condition is not 'fail'. Continuing with the step."
+            echo "PR Condition is not 'success'. Failing the step."
+            exit 1
           fi
       if: github.event_name == 'pull_request'
 
@@ -67,13 +67,13 @@ jobs:
       run: |
           echo  $(ls ${GITHUB_WORKSPACE})
           CONDITION=$(cat ${GITHUB_WORKSPACE}/condition)
-          if [ "$CONDITION" == "fail" ]; then
-            echo "DEPLOY Condition is 'fail'. Failing the step."
-            exit 1
+          if [ "$CONDITION" == "success" ]; then
+            echo "PR Condition is 'success'. Continuing with the step."
           else
-            echo "DEPLOY Condition is not 'fail'. Continuing with the step."
+            echo "PR Condition is not 'success'. Failing the step."
+            exit 1
           fi
-      if: github.event_name == 'push' && steps.test-commit-status-check.PR_COMMIT_STATUS == 'failure'
+      if: github.event_name == 'push' && steps.test-commit-status-check.PR_COMMIT_STATUS != 'success'
 
   deploy:
     needs: test
