next (#7)
* next

* next

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -35,11 +35,11 @@ jobs:
       run: |
           echo  $(ls ${GITHUB_WORKSPACE})
           CONDITION=$(cat ${GITHUB_WORKSPACE}/condition)
-          if [ "$CONDITION" ==   "fail" ]; then
-            echo "PR Condition is 'fail'. Failing the step."
-            exit 1
+          if [ "$CONDITION" == "success" ]; then
+            echo "PR Condition is 'success'. Continuing with the step."
           else
-            echo "PR Condition is not 'fail'. Continuing with the step."
+            echo "PR Condition is not 'success'. Failing the step."
+            exit 1
           fi
       if: github.event_name == 'pull_request'
 
@@ -47,19 +47,25 @@ jobs:
       id: test-commit-status-check
       run: |
           # Extract the pull request number from the GitHub event payload
-
           PULLS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/pulls")
           PR_NUMBER=$(echo "$PULLS" | jq -r '.[-1].number')
           echo "PR_NUMBER $PR_NUMBER"
+
           # Fetch the commits in the pull request
           COMMITS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}/commits")
           echo "LAST COMMITS $COMMITS"
+
           # Extract the SHA of the last commit in the pull request
           LAST_COMMIT=$(echo "$COMMITS" | jq -r '.[-1].sha')
           echo "LAST COMMIT $LAST_COMMIT"
-          PR_BRANCH_COMMIT_STATUS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/commits/$LAST_COMMIT/status" | jq -r '.state')
+
+          # Look for failures in the checks of the commits
+          CHECK_RUNS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/commits/$LAST_COMMIT/check-runs")
+          PR_STATUS=$(echo "$CHECK_RUNS" | jq -r '[ .check_runs[] | select(.conclusion == "failure") | .conclusion] | first // "success"')
+
           echo "PR_COMMIT_STATUS=$PR_BRANCH_COMMIT_STATUS" >> "$GITHUB_OUTPUT"
           echo "COMMIT STATUS $PR_BRANCH_COMMIT_STATUS"
+
       if: github.event_name == 'push'
 
     - name: Run test on deploy
@@ -67,11 +73,11 @@ jobs:
       run: |
           echo  $(ls ${GITHUB_WORKSPACE})
           CONDITION=$(cat ${GITHUB_WORKSPACE}/condition)
-          if [ "$CONDITION" == "fail" ]; then
-            echo "DEPLOY Condition is 'fail'. Failing the step."
-            exit 1
+          if [ "$CONDITION" == "success" ]; then
+            echo "PR Condition is 'success'. Continuing with the step."
           else
-            echo "DEPLOY Condition is not 'fail'. Continuing with the step."
+            echo "PR Condition is not 'success'. Failing the step."
+            exit 1
           fi
       if: github.event_name == 'push' && steps.test-commit-status-check.PR_COMMIT_STATUS == 'failure'
 
